/**
 * Generates structured Obsidian Markdown for a topic
 */
export function generateObsidianMarkdown(topic) {
  if (!topic) return '';

  const tags = (topic.subject || 'computer-science')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .split('-')
    .filter(Boolean)
    .join(', ');

  const dateStr = new Date().toISOString().split('T')[0];

  const md = `---
title: "${topic.title.replace(/"/g, '\\"')}"
subject: "${topic.subject || 'General'}"
metaphor: "${topic.metaphorTitle || ''}"
created: ${dateStr}
tags: [anilearn, ${tags}]
---

# ${topic.title}
> **Anime Mental Model:** *${topic.metaphorTitle}*

## 1. The Anime Metaphor (Feynman ELI5 Intuition)
${topic.metaphorStory}

## 2. Academic Concept & Theoretical Invariants
${topic.academicConcept}

### Core Invariants & Rules
${(topic.keyTakeaways || []).map((k) => `- ${k}`).join('\n')}

## 3. Visual Infographic Hotspots
${(topic.hotspots || []).map((h, i) => `### Hotspot 0${i + 1}: ${h.label} (${h.tag || 'Component'})\n${h.explanation}`).join('\n\n')}

## 4. Mnemonic Cue Cards (Active Recall)
${(topic.visualCueCards || []).map((c, i) => `### Card 0${i + 1}: ${c.title}
- **Visual Anchor:** ${c.visualAnchor}
- **Core Law / Formula:** $${c.formulaOrFact}$
- **Active Intuition Question:** ${c.intuitionQuestion}
- **Recall Answer:** ${c.answer}`).join('\n\n')}

## 5. Diagnostic Active Recall Assessment
${(topic.activeRecallQuiz || []).map((q, i) => `### Question 0${i + 1} [${q.tier || 'Diagnostic'}]: ${q.question}
${q.options.map((opt, optIdx) => `- ${optIdx === q.correctIndex ? '**[CORRECT]**' : '[ ]'} ${opt}`).join('\n')}
*Explanation:* ${q.explanation}`).join('\n\n')}

---
*Generated by AniLearn • Powered by Google DeepMind Gemini 3.8 Flash & Nano Banana*
`;

  return md;
}

/**
 * Generates Anki-compatible TSV text (Tab-Separated Values)
 */
export function generateAnkiDeck(topic) {
  if (!topic) return '';

  const cards = topic.visualCueCards || [];
  const lines = cards.map((c) => {
    const front = `<div style="font-family:sans-serif; text-align:left;">` +
      `<div style="font-size:12px; color:#888; text-transform:uppercase; letter-spacing:1px; margin-bottom:8px;">${topic.title} • Card</div>` +
      `<h3 style="margin:0 0 12px 0; color:#fff;">${c.title}</h3>` +
      `<div style="background:#18181b; padding:12px; border-radius:8px; border:1px solid #333; margin-bottom:12px; color:#ccc;">` +
        `<b>Visual Anchor:</b> ${c.visualAnchor}` +
      `</div>` +
      `<div style="font-size:15px; font-weight:600; color:#eee;">` +
        `${c.intuitionQuestion}` +
      `</div>` +
    `</div>`;

    const back = `<div style="font-family:sans-serif; text-align:left;">` +
      `<div style="background:#09090b; padding:10px 14px; border-radius:8px; border:1px solid #27272a; margin-bottom:12px;">` +
        `<span style="font-size:11px; color:#a1a1aa; text-transform:uppercase;">Core Law:</span>` +
        `<div style="font-size:16px; font-weight:bold; color:#fff; margin-top:4px;">\\[${c.formulaOrFact}\\]</div>` +
      `</div>` +
      `<div style="color:#d4d4d8; font-size:14px; line-height:1.6;">` +
        `<b>Recall Answer:</b> ${c.answer}` +
      `</div>` +
    `</div>`;

    const tags = `AniLearn ${topic.subject?.replace(/[^a-zA-Z0-9]/g, '_') || 'Computer_Science'}`;
    const cleanFront = front.replace(/\t/g, ' ').replace(/\n/g, '<br>');
    const cleanBack = back.replace(/\t/g, ' ').replace(/\n/g, '<br>');

    return `${cleanFront}\t${cleanBack}\t${tags}`;
  });

  return lines.join('\n');
}

/**
 * Triggers file download in the browser
 */
export function downloadFile(content, fileName, mimeType = 'text/plain;charset=utf-8') {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
